# Generated by Django 5.1.1 on 2024-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_album_app', '0003_remove_photo_description_alter_album_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
