# Generated by Django 5.1.1 on 2024-10-15 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_album_app', '0004_rename_created_at_photo_added_at_alter_album_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.ImageField(upload_to='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='wedding_album_app.photo')),
            ],
        ),
    ]
